# Generated by Django 6.1 on 2026-09-28 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reposteria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='porciones',
            field=models.CharField(blank=True, help_text='Ej: 8-10 porciones', max_length=50, null=True),
        ),
    ]
